/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectTenantRouteImport } from './routes/select-tenant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as UserSettingsRouteRouteImport } from './routes/user-settings/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserSettingsIndexRouteImport } from './routes/user-settings/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as UserSettingsSecurityRouteImport } from './routes/user-settings/security'
import { Route as UserSettingsProfileRouteImport } from './routes/user-settings/profile'
import { Route as UserSettingsPreferencesRouteImport } from './routes/user-settings/preferences'
import { Route as TeamAccessTokenRouteImport } from './routes/team-access/$token'
import { Route as SettingsTenantMembersRouteImport } from './routes/settings/tenant-members'
import { Route as SettingsPermissionsRouteImport } from './routes/settings/permissions'
import { Route as SettingsOrganizationRouteImport } from './routes/settings/organization'
import { Route as SettingsMatchRulesRouteImport } from './routes/settings/match-rules'
import { Route as SettingsDefaultsRouteImport } from './routes/settings/defaults'
import { Route as TournamentsTournamentIdRouteRouteImport } from './routes/tournaments/$tournamentId/route'
import { Route as TournamentsTournamentIdIndexRouteImport } from './routes/tournaments/$tournamentId/index'
import { Route as MatchesMatchIdIndexRouteImport } from './routes/matches/$matchId/index'
import { Route as TournamentsTournamentIdStatsRouteImport } from './routes/tournaments/$tournamentId/stats'
import { Route as TournamentsTournamentIdStandingsRouteImport } from './routes/tournaments/$tournamentId/standings'
import { Route as TournamentsTournamentIdFixturesRouteImport } from './routes/tournaments/$tournamentId/fixtures'
import { Route as TeamsTeamIdPlayersRouteImport } from './routes/teams/$teamId/players'
import { Route as MatchesMatchIdStartRouteImport } from './routes/matches/$matchId/start'
import { Route as MatchesMatchIdScoreRouteImport } from './routes/matches/$matchId/score'
import { Route as MatchesMatchIdRosterRouteImport } from './routes/matches/$matchId/roster'
import { Route as TournamentsTournamentIdTeamsRouteRouteImport } from './routes/tournaments/$tournamentId/teams/route'
import { Route as TournamentsTournamentIdTeamsIndexRouteImport } from './routes/tournaments/$tournamentId/teams/index'
import { Route as TournamentsTournamentIdMatchesMatchIdIndexRouteImport } from './routes/tournaments/$tournamentId/matches/$matchId/index'
import { Route as TournamentsTournamentIdTeamsTeamIdPlayersRouteImport } from './routes/tournaments/$tournamentId/teams/$teamId/players'
import { Route as TournamentsTournamentIdMatchesMatchIdSummaryRouteImport } from './routes/tournaments/$tournamentId/matches/$matchId/summary'
import { Route as TournamentsTournamentIdMatchesMatchIdStartRouteImport } from './routes/tournaments/$tournamentId/matches/$matchId/start'
import { Route as TournamentsTournamentIdMatchesMatchIdScoreRouteImport } from './routes/tournaments/$tournamentId/matches/$matchId/score'
import { Route as TournamentsTournamentIdMatchesMatchIdRosterRouteImport } from './routes/tournaments/$tournamentId/matches/$matchId/roster'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectTenantRoute = SelectTenantRouteImport.update({
  id: '/select-tenant',
  path: '/select-tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsRouteRoute = UserSettingsRouteRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsIndexRoute = UserSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserSettingsRouteRoute,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const UserSettingsSecurityRoute = UserSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => UserSettingsRouteRoute,
} as any)
const UserSettingsProfileRoute = UserSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserSettingsRouteRoute,
} as any)
const UserSettingsPreferencesRoute = UserSettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => UserSettingsRouteRoute,
} as any)
const TeamAccessTokenRoute = TeamAccessTokenRouteImport.update({
  id: '/team-access/$token',
  path: '/team-access/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTenantMembersRoute = SettingsTenantMembersRouteImport.update({
  id: '/tenant-members',
  path: '/tenant-members',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPermissionsRoute = SettingsPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsMatchRulesRoute = SettingsMatchRulesRouteImport.update({
  id: '/match-rules',
  path: '/match-rules',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsDefaultsRoute = SettingsDefaultsRouteImport.update({
  id: '/defaults',
  path: '/defaults',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const TournamentsTournamentIdRouteRoute =
  TournamentsTournamentIdRouteRouteImport.update({
    id: '/tournaments/$tournamentId',
    path: '/tournaments/$tournamentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsTournamentIdIndexRoute =
  TournamentsTournamentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TournamentsTournamentIdRouteRoute,
  } as any)
const MatchesMatchIdIndexRoute = MatchesMatchIdIndexRouteImport.update({
  id: '/matches/$matchId/',
  path: '/matches/$matchId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdStatsRoute =
  TournamentsTournamentIdStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => TournamentsTournamentIdRouteRoute,
  } as any)
const TournamentsTournamentIdStandingsRoute =
  TournamentsTournamentIdStandingsRouteImport.update({
    id: '/standings',
    path: '/standings',
    getParentRoute: () => TournamentsTournamentIdRouteRoute,
  } as any)
const TournamentsTournamentIdFixturesRoute =
  TournamentsTournamentIdFixturesRouteImport.update({
    id: '/fixtures',
    path: '/fixtures',
    getParentRoute: () => TournamentsTournamentIdRouteRoute,
  } as any)
const TeamsTeamIdPlayersRoute = TeamsTeamIdPlayersRouteImport.update({
  id: '/teams/$teamId/players',
  path: '/teams/$teamId/players',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdStartRoute = MatchesMatchIdStartRouteImport.update({
  id: '/matches/$matchId/start',
  path: '/matches/$matchId/start',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdScoreRoute = MatchesMatchIdScoreRouteImport.update({
  id: '/matches/$matchId/score',
  path: '/matches/$matchId/score',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRosterRoute = MatchesMatchIdRosterRouteImport.update({
  id: '/matches/$matchId/roster',
  path: '/matches/$matchId/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdTeamsRouteRoute =
  TournamentsTournamentIdTeamsRouteRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => TournamentsTournamentIdRouteRoute,
  } as any)
const TournamentsTournamentIdTeamsIndexRoute =
  TournamentsTournamentIdTeamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => TournamentsTournamentIdTeamsRouteRoute,
  } as any)
const TournamentsTournamentIdMatchesMatchIdIndexRoute =
  TournamentsTournamentIdMatchesMatchIdIndexRouteImport.update({
    id: '/matches/$matchId/',
    path: '/matches/$matchId/',
    getParentRoute: () => TournamentsTournamentIdRouteRoute,
  } as any)
const TournamentsTournamentIdTeamsTeamIdPlayersRoute =
  TournamentsTournamentIdTeamsTeamIdPlayersRouteImport.update({
    id: '/$teamId/players',
    path: '/$teamId/players',
    getParentRoute: () => TournamentsTournamentIdTeamsRouteRoute,
  } as any)
const TournamentsTournamentIdMatchesMatchIdSummaryRoute =
  TournamentsTournamentIdMatchesMatchIdSummaryRouteImport.update({
    id: '/matches/$matchId/summary',
    path: '/matches/$matchId/summary',
    getParentRoute: () => TournamentsTournamentIdRouteRoute,
  } as any)
const TournamentsTournamentIdMatchesMatchIdStartRoute =
  TournamentsTournamentIdMatchesMatchIdStartRouteImport.update({
    id: '/matches/$matchId/start',
    path: '/matches/$matchId/start',
    getParentRoute: () => TournamentsTournamentIdRouteRoute,
  } as any)
const TournamentsTournamentIdMatchesMatchIdScoreRoute =
  TournamentsTournamentIdMatchesMatchIdScoreRouteImport.update({
    id: '/matches/$matchId/score',
    path: '/matches/$matchId/score',
    getParentRoute: () => TournamentsTournamentIdRouteRoute,
  } as any)
const TournamentsTournamentIdMatchesMatchIdRosterRoute =
  TournamentsTournamentIdMatchesMatchIdRosterRouteImport.update({
    id: '/matches/$matchId/roster',
    path: '/matches/$matchId/roster',
    getParentRoute: () => TournamentsTournamentIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/user-settings': typeof UserSettingsRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/select-tenant': typeof SelectTenantRoute
  '/signup': typeof SignupRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRouteRouteWithChildren
  '/settings/defaults': typeof SettingsDefaultsRoute
  '/settings/match-rules': typeof SettingsMatchRulesRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/tenant-members': typeof SettingsTenantMembersRoute
  '/team-access/$token': typeof TeamAccessTokenRoute
  '/user-settings/preferences': typeof UserSettingsPreferencesRoute
  '/user-settings/profile': typeof UserSettingsProfileRoute
  '/user-settings/security': typeof UserSettingsSecurityRoute
  '/settings/': typeof SettingsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/user-settings/': typeof UserSettingsIndexRoute
  '/tournaments/$tournamentId/teams': typeof TournamentsTournamentIdTeamsRouteRouteWithChildren
  '/matches/$matchId/roster': typeof MatchesMatchIdRosterRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
  '/matches/$matchId/start': typeof MatchesMatchIdStartRoute
  '/teams/$teamId/players': typeof TeamsTeamIdPlayersRoute
  '/tournaments/$tournamentId/fixtures': typeof TournamentsTournamentIdFixturesRoute
  '/tournaments/$tournamentId/standings': typeof TournamentsTournamentIdStandingsRoute
  '/tournaments/$tournamentId/stats': typeof TournamentsTournamentIdStatsRoute
  '/matches/$matchId/': typeof MatchesMatchIdIndexRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
  '/tournaments/$tournamentId/teams/': typeof TournamentsTournamentIdTeamsIndexRoute
  '/tournaments/$tournamentId/matches/$matchId/roster': typeof TournamentsTournamentIdMatchesMatchIdRosterRoute
  '/tournaments/$tournamentId/matches/$matchId/score': typeof TournamentsTournamentIdMatchesMatchIdScoreRoute
  '/tournaments/$tournamentId/matches/$matchId/start': typeof TournamentsTournamentIdMatchesMatchIdStartRoute
  '/tournaments/$tournamentId/matches/$matchId/summary': typeof TournamentsTournamentIdMatchesMatchIdSummaryRoute
  '/tournaments/$tournamentId/teams/$teamId/players': typeof TournamentsTournamentIdTeamsTeamIdPlayersRoute
  '/tournaments/$tournamentId/matches/$matchId/': typeof TournamentsTournamentIdMatchesMatchIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/select-tenant': typeof SelectTenantRoute
  '/signup': typeof SignupRoute
  '/settings/defaults': typeof SettingsDefaultsRoute
  '/settings/match-rules': typeof SettingsMatchRulesRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/tenant-members': typeof SettingsTenantMembersRoute
  '/team-access/$token': typeof TeamAccessTokenRoute
  '/user-settings/preferences': typeof UserSettingsPreferencesRoute
  '/user-settings/profile': typeof UserSettingsProfileRoute
  '/user-settings/security': typeof UserSettingsSecurityRoute
  '/settings': typeof SettingsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/user-settings': typeof UserSettingsIndexRoute
  '/matches/$matchId/roster': typeof MatchesMatchIdRosterRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
  '/matches/$matchId/start': typeof MatchesMatchIdStartRoute
  '/teams/$teamId/players': typeof TeamsTeamIdPlayersRoute
  '/tournaments/$tournamentId/fixtures': typeof TournamentsTournamentIdFixturesRoute
  '/tournaments/$tournamentId/standings': typeof TournamentsTournamentIdStandingsRoute
  '/tournaments/$tournamentId/stats': typeof TournamentsTournamentIdStatsRoute
  '/matches/$matchId': typeof MatchesMatchIdIndexRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdIndexRoute
  '/tournaments/$tournamentId/teams': typeof TournamentsTournamentIdTeamsIndexRoute
  '/tournaments/$tournamentId/matches/$matchId/roster': typeof TournamentsTournamentIdMatchesMatchIdRosterRoute
  '/tournaments/$tournamentId/matches/$matchId/score': typeof TournamentsTournamentIdMatchesMatchIdScoreRoute
  '/tournaments/$tournamentId/matches/$matchId/start': typeof TournamentsTournamentIdMatchesMatchIdStartRoute
  '/tournaments/$tournamentId/matches/$matchId/summary': typeof TournamentsTournamentIdMatchesMatchIdSummaryRoute
  '/tournaments/$tournamentId/teams/$teamId/players': typeof TournamentsTournamentIdTeamsTeamIdPlayersRoute
  '/tournaments/$tournamentId/matches/$matchId': typeof TournamentsTournamentIdMatchesMatchIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/user-settings': typeof UserSettingsRouteRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/forbidden': typeof ForbiddenRoute
  '/login': typeof LoginRoute
  '/select-tenant': typeof SelectTenantRoute
  '/signup': typeof SignupRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRouteRouteWithChildren
  '/settings/defaults': typeof SettingsDefaultsRoute
  '/settings/match-rules': typeof SettingsMatchRulesRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/permissions': typeof SettingsPermissionsRoute
  '/settings/tenant-members': typeof SettingsTenantMembersRoute
  '/team-access/$token': typeof TeamAccessTokenRoute
  '/user-settings/preferences': typeof UserSettingsPreferencesRoute
  '/user-settings/profile': typeof UserSettingsProfileRoute
  '/user-settings/security': typeof UserSettingsSecurityRoute
  '/settings/': typeof SettingsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/user-settings/': typeof UserSettingsIndexRoute
  '/tournaments/$tournamentId/teams': typeof TournamentsTournamentIdTeamsRouteRouteWithChildren
  '/matches/$matchId/roster': typeof MatchesMatchIdRosterRoute
  '/matches/$matchId/score': typeof MatchesMatchIdScoreRoute
  '/matches/$matchId/start': typeof MatchesMatchIdStartRoute
  '/teams/$teamId/players': typeof TeamsTeamIdPlayersRoute
  '/tournaments/$tournamentId/fixtures': typeof TournamentsTournamentIdFixturesRoute
  '/tournaments/$tournamentId/standings': typeof TournamentsTournamentIdStandingsRoute
  '/tournaments/$tournamentId/stats': typeof TournamentsTournamentIdStatsRoute
  '/matches/$matchId/': typeof MatchesMatchIdIndexRoute
  '/tournaments/$tournamentId/': typeof TournamentsTournamentIdIndexRoute
  '/tournaments/$tournamentId/teams/': typeof TournamentsTournamentIdTeamsIndexRoute
  '/tournaments/$tournamentId/matches/$matchId/roster': typeof TournamentsTournamentIdMatchesMatchIdRosterRoute
  '/tournaments/$tournamentId/matches/$matchId/score': typeof TournamentsTournamentIdMatchesMatchIdScoreRoute
  '/tournaments/$tournamentId/matches/$matchId/start': typeof TournamentsTournamentIdMatchesMatchIdStartRoute
  '/tournaments/$tournamentId/matches/$matchId/summary': typeof TournamentsTournamentIdMatchesMatchIdSummaryRoute
  '/tournaments/$tournamentId/teams/$teamId/players': typeof TournamentsTournamentIdTeamsTeamIdPlayersRoute
  '/tournaments/$tournamentId/matches/$matchId/': typeof TournamentsTournamentIdMatchesMatchIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/user-settings'
    | '/dashboard'
    | '/forbidden'
    | '/login'
    | '/select-tenant'
    | '/signup'
    | '/tournaments/$tournamentId'
    | '/settings/defaults'
    | '/settings/match-rules'
    | '/settings/organization'
    | '/settings/permissions'
    | '/settings/tenant-members'
    | '/team-access/$token'
    | '/user-settings/preferences'
    | '/user-settings/profile'
    | '/user-settings/security'
    | '/settings/'
    | '/tournaments/'
    | '/user-settings/'
    | '/tournaments/$tournamentId/teams'
    | '/matches/$matchId/roster'
    | '/matches/$matchId/score'
    | '/matches/$matchId/start'
    | '/teams/$teamId/players'
    | '/tournaments/$tournamentId/fixtures'
    | '/tournaments/$tournamentId/standings'
    | '/tournaments/$tournamentId/stats'
    | '/matches/$matchId/'
    | '/tournaments/$tournamentId/'
    | '/tournaments/$tournamentId/teams/'
    | '/tournaments/$tournamentId/matches/$matchId/roster'
    | '/tournaments/$tournamentId/matches/$matchId/score'
    | '/tournaments/$tournamentId/matches/$matchId/start'
    | '/tournaments/$tournamentId/matches/$matchId/summary'
    | '/tournaments/$tournamentId/teams/$teamId/players'
    | '/tournaments/$tournamentId/matches/$matchId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forbidden'
    | '/login'
    | '/select-tenant'
    | '/signup'
    | '/settings/defaults'
    | '/settings/match-rules'
    | '/settings/organization'
    | '/settings/permissions'
    | '/settings/tenant-members'
    | '/team-access/$token'
    | '/user-settings/preferences'
    | '/user-settings/profile'
    | '/user-settings/security'
    | '/settings'
    | '/tournaments'
    | '/user-settings'
    | '/matches/$matchId/roster'
    | '/matches/$matchId/score'
    | '/matches/$matchId/start'
    | '/teams/$teamId/players'
    | '/tournaments/$tournamentId/fixtures'
    | '/tournaments/$tournamentId/standings'
    | '/tournaments/$tournamentId/stats'
    | '/matches/$matchId'
    | '/tournaments/$tournamentId'
    | '/tournaments/$tournamentId/teams'
    | '/tournaments/$tournamentId/matches/$matchId/roster'
    | '/tournaments/$tournamentId/matches/$matchId/score'
    | '/tournaments/$tournamentId/matches/$matchId/start'
    | '/tournaments/$tournamentId/matches/$matchId/summary'
    | '/tournaments/$tournamentId/teams/$teamId/players'
    | '/tournaments/$tournamentId/matches/$matchId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/user-settings'
    | '/dashboard'
    | '/forbidden'
    | '/login'
    | '/select-tenant'
    | '/signup'
    | '/tournaments/$tournamentId'
    | '/settings/defaults'
    | '/settings/match-rules'
    | '/settings/organization'
    | '/settings/permissions'
    | '/settings/tenant-members'
    | '/team-access/$token'
    | '/user-settings/preferences'
    | '/user-settings/profile'
    | '/user-settings/security'
    | '/settings/'
    | '/tournaments/'
    | '/user-settings/'
    | '/tournaments/$tournamentId/teams'
    | '/matches/$matchId/roster'
    | '/matches/$matchId/score'
    | '/matches/$matchId/start'
    | '/teams/$teamId/players'
    | '/tournaments/$tournamentId/fixtures'
    | '/tournaments/$tournamentId/standings'
    | '/tournaments/$tournamentId/stats'
    | '/matches/$matchId/'
    | '/tournaments/$tournamentId/'
    | '/tournaments/$tournamentId/teams/'
    | '/tournaments/$tournamentId/matches/$matchId/roster'
    | '/tournaments/$tournamentId/matches/$matchId/score'
    | '/tournaments/$tournamentId/matches/$matchId/start'
    | '/tournaments/$tournamentId/matches/$matchId/summary'
    | '/tournaments/$tournamentId/teams/$teamId/players'
    | '/tournaments/$tournamentId/matches/$matchId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  UserSettingsRouteRoute: typeof UserSettingsRouteRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  SelectTenantRoute: typeof SelectTenantRoute
  SignupRoute: typeof SignupRoute
  TournamentsTournamentIdRouteRoute: typeof TournamentsTournamentIdRouteRouteWithChildren
  TeamAccessTokenRoute: typeof TeamAccessTokenRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  MatchesMatchIdRosterRoute: typeof MatchesMatchIdRosterRoute
  MatchesMatchIdScoreRoute: typeof MatchesMatchIdScoreRoute
  MatchesMatchIdStartRoute: typeof MatchesMatchIdStartRoute
  TeamsTeamIdPlayersRoute: typeof TeamsTeamIdPlayersRoute
  MatchesMatchIdIndexRoute: typeof MatchesMatchIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-tenant': {
      id: '/select-tenant'
      path: '/select-tenant'
      fullPath: '/select-tenant'
      preLoaderRoute: typeof SelectTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-settings': {
      id: '/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof UserSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-settings/': {
      id: '/user-settings/'
      path: '/'
      fullPath: '/user-settings/'
      preLoaderRoute: typeof UserSettingsIndexRouteImport
      parentRoute: typeof UserSettingsRouteRoute
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/user-settings/security': {
      id: '/user-settings/security'
      path: '/security'
      fullPath: '/user-settings/security'
      preLoaderRoute: typeof UserSettingsSecurityRouteImport
      parentRoute: typeof UserSettingsRouteRoute
    }
    '/user-settings/profile': {
      id: '/user-settings/profile'
      path: '/profile'
      fullPath: '/user-settings/profile'
      preLoaderRoute: typeof UserSettingsProfileRouteImport
      parentRoute: typeof UserSettingsRouteRoute
    }
    '/user-settings/preferences': {
      id: '/user-settings/preferences'
      path: '/preferences'
      fullPath: '/user-settings/preferences'
      preLoaderRoute: typeof UserSettingsPreferencesRouteImport
      parentRoute: typeof UserSettingsRouteRoute
    }
    '/team-access/$token': {
      id: '/team-access/$token'
      path: '/team-access/$token'
      fullPath: '/team-access/$token'
      preLoaderRoute: typeof TeamAccessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tenant-members': {
      id: '/settings/tenant-members'
      path: '/tenant-members'
      fullPath: '/settings/tenant-members'
      preLoaderRoute: typeof SettingsTenantMembersRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/permissions': {
      id: '/settings/permissions'
      path: '/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof SettingsPermissionsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/organization': {
      id: '/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/match-rules': {
      id: '/settings/match-rules'
      path: '/match-rules'
      fullPath: '/settings/match-rules'
      preLoaderRoute: typeof SettingsMatchRulesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/defaults': {
      id: '/settings/defaults'
      path: '/defaults'
      fullPath: '/settings/defaults'
      preLoaderRoute: typeof SettingsDefaultsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/tournaments/$tournamentId': {
      id: '/tournaments/$tournamentId'
      path: '/tournaments/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/': {
      id: '/tournaments/$tournamentId/'
      path: '/'
      fullPath: '/tournaments/$tournamentId/'
      preLoaderRoute: typeof TournamentsTournamentIdIndexRouteImport
      parentRoute: typeof TournamentsTournamentIdRouteRoute
    }
    '/matches/$matchId/': {
      id: '/matches/$matchId/'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId/'
      preLoaderRoute: typeof MatchesMatchIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/stats': {
      id: '/tournaments/$tournamentId/stats'
      path: '/stats'
      fullPath: '/tournaments/$tournamentId/stats'
      preLoaderRoute: typeof TournamentsTournamentIdStatsRouteImport
      parentRoute: typeof TournamentsTournamentIdRouteRoute
    }
    '/tournaments/$tournamentId/standings': {
      id: '/tournaments/$tournamentId/standings'
      path: '/standings'
      fullPath: '/tournaments/$tournamentId/standings'
      preLoaderRoute: typeof TournamentsTournamentIdStandingsRouteImport
      parentRoute: typeof TournamentsTournamentIdRouteRoute
    }
    '/tournaments/$tournamentId/fixtures': {
      id: '/tournaments/$tournamentId/fixtures'
      path: '/fixtures'
      fullPath: '/tournaments/$tournamentId/fixtures'
      preLoaderRoute: typeof TournamentsTournamentIdFixturesRouteImport
      parentRoute: typeof TournamentsTournamentIdRouteRoute
    }
    '/teams/$teamId/players': {
      id: '/teams/$teamId/players'
      path: '/teams/$teamId/players'
      fullPath: '/teams/$teamId/players'
      preLoaderRoute: typeof TeamsTeamIdPlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId/start': {
      id: '/matches/$matchId/start'
      path: '/matches/$matchId/start'
      fullPath: '/matches/$matchId/start'
      preLoaderRoute: typeof MatchesMatchIdStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId/score': {
      id: '/matches/$matchId/score'
      path: '/matches/$matchId/score'
      fullPath: '/matches/$matchId/score'
      preLoaderRoute: typeof MatchesMatchIdScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId/roster': {
      id: '/matches/$matchId/roster'
      path: '/matches/$matchId/roster'
      fullPath: '/matches/$matchId/roster'
      preLoaderRoute: typeof MatchesMatchIdRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId/teams': {
      id: '/tournaments/$tournamentId/teams'
      path: '/teams'
      fullPath: '/tournaments/$tournamentId/teams'
      preLoaderRoute: typeof TournamentsTournamentIdTeamsRouteRouteImport
      parentRoute: typeof TournamentsTournamentIdRouteRoute
    }
    '/tournaments/$tournamentId/teams/': {
      id: '/tournaments/$tournamentId/teams/'
      path: '/'
      fullPath: '/tournaments/$tournamentId/teams/'
      preLoaderRoute: typeof TournamentsTournamentIdTeamsIndexRouteImport
      parentRoute: typeof TournamentsTournamentIdTeamsRouteRoute
    }
    '/tournaments/$tournamentId/matches/$matchId/': {
      id: '/tournaments/$tournamentId/matches/$matchId/'
      path: '/matches/$matchId'
      fullPath: '/tournaments/$tournamentId/matches/$matchId/'
      preLoaderRoute: typeof TournamentsTournamentIdMatchesMatchIdIndexRouteImport
      parentRoute: typeof TournamentsTournamentIdRouteRoute
    }
    '/tournaments/$tournamentId/teams/$teamId/players': {
      id: '/tournaments/$tournamentId/teams/$teamId/players'
      path: '/$teamId/players'
      fullPath: '/tournaments/$tournamentId/teams/$teamId/players'
      preLoaderRoute: typeof TournamentsTournamentIdTeamsTeamIdPlayersRouteImport
      parentRoute: typeof TournamentsTournamentIdTeamsRouteRoute
    }
    '/tournaments/$tournamentId/matches/$matchId/summary': {
      id: '/tournaments/$tournamentId/matches/$matchId/summary'
      path: '/matches/$matchId/summary'
      fullPath: '/tournaments/$tournamentId/matches/$matchId/summary'
      preLoaderRoute: typeof TournamentsTournamentIdMatchesMatchIdSummaryRouteImport
      parentRoute: typeof TournamentsTournamentIdRouteRoute
    }
    '/tournaments/$tournamentId/matches/$matchId/start': {
      id: '/tournaments/$tournamentId/matches/$matchId/start'
      path: '/matches/$matchId/start'
      fullPath: '/tournaments/$tournamentId/matches/$matchId/start'
      preLoaderRoute: typeof TournamentsTournamentIdMatchesMatchIdStartRouteImport
      parentRoute: typeof TournamentsTournamentIdRouteRoute
    }
    '/tournaments/$tournamentId/matches/$matchId/score': {
      id: '/tournaments/$tournamentId/matches/$matchId/score'
      path: '/matches/$matchId/score'
      fullPath: '/tournaments/$tournamentId/matches/$matchId/score'
      preLoaderRoute: typeof TournamentsTournamentIdMatchesMatchIdScoreRouteImport
      parentRoute: typeof TournamentsTournamentIdRouteRoute
    }
    '/tournaments/$tournamentId/matches/$matchId/roster': {
      id: '/tournaments/$tournamentId/matches/$matchId/roster'
      path: '/matches/$matchId/roster'
      fullPath: '/tournaments/$tournamentId/matches/$matchId/roster'
      preLoaderRoute: typeof TournamentsTournamentIdMatchesMatchIdRosterRouteImport
      parentRoute: typeof TournamentsTournamentIdRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsDefaultsRoute: typeof SettingsDefaultsRoute
  SettingsMatchRulesRoute: typeof SettingsMatchRulesRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  SettingsPermissionsRoute: typeof SettingsPermissionsRoute
  SettingsTenantMembersRoute: typeof SettingsTenantMembersRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsDefaultsRoute: SettingsDefaultsRoute,
  SettingsMatchRulesRoute: SettingsMatchRulesRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  SettingsPermissionsRoute: SettingsPermissionsRoute,
  SettingsTenantMembersRoute: SettingsTenantMembersRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface UserSettingsRouteRouteChildren {
  UserSettingsPreferencesRoute: typeof UserSettingsPreferencesRoute
  UserSettingsProfileRoute: typeof UserSettingsProfileRoute
  UserSettingsSecurityRoute: typeof UserSettingsSecurityRoute
  UserSettingsIndexRoute: typeof UserSettingsIndexRoute
}

const UserSettingsRouteRouteChildren: UserSettingsRouteRouteChildren = {
  UserSettingsPreferencesRoute: UserSettingsPreferencesRoute,
  UserSettingsProfileRoute: UserSettingsProfileRoute,
  UserSettingsSecurityRoute: UserSettingsSecurityRoute,
  UserSettingsIndexRoute: UserSettingsIndexRoute,
}

const UserSettingsRouteRouteWithChildren =
  UserSettingsRouteRoute._addFileChildren(UserSettingsRouteRouteChildren)

interface TournamentsTournamentIdTeamsRouteRouteChildren {
  TournamentsTournamentIdTeamsIndexRoute: typeof TournamentsTournamentIdTeamsIndexRoute
  TournamentsTournamentIdTeamsTeamIdPlayersRoute: typeof TournamentsTournamentIdTeamsTeamIdPlayersRoute
}

const TournamentsTournamentIdTeamsRouteRouteChildren: TournamentsTournamentIdTeamsRouteRouteChildren =
  {
    TournamentsTournamentIdTeamsIndexRoute:
      TournamentsTournamentIdTeamsIndexRoute,
    TournamentsTournamentIdTeamsTeamIdPlayersRoute:
      TournamentsTournamentIdTeamsTeamIdPlayersRoute,
  }

const TournamentsTournamentIdTeamsRouteRouteWithChildren =
  TournamentsTournamentIdTeamsRouteRoute._addFileChildren(
    TournamentsTournamentIdTeamsRouteRouteChildren,
  )

interface TournamentsTournamentIdRouteRouteChildren {
  TournamentsTournamentIdTeamsRouteRoute: typeof TournamentsTournamentIdTeamsRouteRouteWithChildren
  TournamentsTournamentIdFixturesRoute: typeof TournamentsTournamentIdFixturesRoute
  TournamentsTournamentIdStandingsRoute: typeof TournamentsTournamentIdStandingsRoute
  TournamentsTournamentIdStatsRoute: typeof TournamentsTournamentIdStatsRoute
  TournamentsTournamentIdIndexRoute: typeof TournamentsTournamentIdIndexRoute
  TournamentsTournamentIdMatchesMatchIdRosterRoute: typeof TournamentsTournamentIdMatchesMatchIdRosterRoute
  TournamentsTournamentIdMatchesMatchIdScoreRoute: typeof TournamentsTournamentIdMatchesMatchIdScoreRoute
  TournamentsTournamentIdMatchesMatchIdStartRoute: typeof TournamentsTournamentIdMatchesMatchIdStartRoute
  TournamentsTournamentIdMatchesMatchIdSummaryRoute: typeof TournamentsTournamentIdMatchesMatchIdSummaryRoute
  TournamentsTournamentIdMatchesMatchIdIndexRoute: typeof TournamentsTournamentIdMatchesMatchIdIndexRoute
}

const TournamentsTournamentIdRouteRouteChildren: TournamentsTournamentIdRouteRouteChildren =
  {
    TournamentsTournamentIdTeamsRouteRoute:
      TournamentsTournamentIdTeamsRouteRouteWithChildren,
    TournamentsTournamentIdFixturesRoute: TournamentsTournamentIdFixturesRoute,
    TournamentsTournamentIdStandingsRoute:
      TournamentsTournamentIdStandingsRoute,
    TournamentsTournamentIdStatsRoute: TournamentsTournamentIdStatsRoute,
    TournamentsTournamentIdIndexRoute: TournamentsTournamentIdIndexRoute,
    TournamentsTournamentIdMatchesMatchIdRosterRoute:
      TournamentsTournamentIdMatchesMatchIdRosterRoute,
    TournamentsTournamentIdMatchesMatchIdScoreRoute:
      TournamentsTournamentIdMatchesMatchIdScoreRoute,
    TournamentsTournamentIdMatchesMatchIdStartRoute:
      TournamentsTournamentIdMatchesMatchIdStartRoute,
    TournamentsTournamentIdMatchesMatchIdSummaryRoute:
      TournamentsTournamentIdMatchesMatchIdSummaryRoute,
    TournamentsTournamentIdMatchesMatchIdIndexRoute:
      TournamentsTournamentIdMatchesMatchIdIndexRoute,
  }

const TournamentsTournamentIdRouteRouteWithChildren =
  TournamentsTournamentIdRouteRoute._addFileChildren(
    TournamentsTournamentIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  UserSettingsRouteRoute: UserSettingsRouteRouteWithChildren,
  DashboardRoute: DashboardRoute,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  SelectTenantRoute: SelectTenantRoute,
  SignupRoute: SignupRoute,
  TournamentsTournamentIdRouteRoute:
    TournamentsTournamentIdRouteRouteWithChildren,
  TeamAccessTokenRoute: TeamAccessTokenRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  MatchesMatchIdRosterRoute: MatchesMatchIdRosterRoute,
  MatchesMatchIdScoreRoute: MatchesMatchIdScoreRoute,
  MatchesMatchIdStartRoute: MatchesMatchIdStartRoute,
  TeamsTeamIdPlayersRoute: TeamsTeamIdPlayersRoute,
  MatchesMatchIdIndexRoute: MatchesMatchIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
